### ISSUE TITLE
iOS7 wrong layout issue

### ISSUE THREAD

**Issue by susieyy** [appsocially/AppSocially-iOS-SDK#2]
Wrong layout issue only iOS7.

LINE
![screenshot 2013 10 30 13 17 35](https://f.cloud.github.com/assets/62295/1434468/df4ae898-411a-11e3-995c-c931a26ebde2.png)

Share
![screenshot 2013 10 30 13 11 09](https://f.cloud.github.com/assets/62295/1434469/e7fbebe0-411a-11e3-9a97-7a95ccddb2f9.png)

Mail (Lost inputting text at your name and To:)
![screenshot 2013 10 30 13 11 36](https://f.cloud.github.com/assets/62295/1434471/ed7db9cc-411a-11e3-8de3-d9d1cf8ac0eb.png)

**Comment by shu223** [comment]
Thanks, we will fix these problems soon!
