### ISSUE TITLE
Sample App: FirstSample Permission bug

### ISSUE THREAD

**Issue by vleango** [appsocially/AppSocially-iOS-SDK#4]
When sending an invite through Facebook, a message appears asking to allow "FirstSample" some facebook permissions.

Even after clicking on ok, the "No Permissions" message appears.

using a real device, with Facebook integration on. (and "FirstSample" facebook permission is on as well)

**Comment by aerodynamics** [comment]
Hi @vleango , We couldn't reproduce the same error on our environment (iPhone5s with iOS 7.0.4). When "permission off," it causes an error of "no permission," but when it's "on," it doen't cause errors of "no permission." Does it happen the same ways also with other samples? Thanks, Yusuke

**Comment by nariakiiwatani** [comment]
I got the same error and got fixed.
@vleango I guess you haven't add platform setting to your facebook app.
please go to your facebook app page --> Setting --> Basic --> Add Platform.
Input "Bundle ID" and switch "Single Sine On" to YES.
"Save Changes" then my app works fine.

Hope it helps!
