### ISSUE TITLE
ASFriendPickerViewController send button not show in search view

### ISSUE THREAD

**Issue by modenl** [appsocially/AppSocially-iOS-SDK#6]
When multiSelectEnabled set to YES, we have to cancel search before send.

**Comment by aerodynamics** [comment]
Thanks for letting us know. We are updating it now.

**Comment by modenl** [comment]
Send button still not show up when user start to search in ASFriendPickerViewController. But I found a workaround: Add a send button as optionalBtn and simulate sendButton touch.
